const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../public/baduk/engine'),L=require('../public/baduk/lessons');
test('Go supply: size limits, legal moves spend stones, pass/illegal moves do not',()=>{
 for(const [n,b,w]of [[9,41,40],[13,85,84],[19,181,180]]){const s=E.initialState(n);assert.equal(E.remaining(s,1),b);assert.equal(E.remaining(s,2),w);const t=E.play(s,0);assert.equal(E.remaining(t,1),b-1);assert.equal(E.remaining(E.play(t,null),2),w);assert.throws(()=>E.play(t,0));assert.equal(E.remaining(t,2),w);}
});
test('Go supply: captured stones are not replenished; exhausted AI passes; both can finish',()=>{
 let s=setup([7,11,13],[12]);const before=E.remaining(s,2);s=E.play(s,17);assert.equal(E.remaining(s,2),before);
 s=E.initialState(9);s.captures=[0,40,41];
 assert.equal(E.remaining(s,1),0);assert.equal(E.remaining(s,2),0);
 for(const level of [0,1,2,3])assert.equal(E.suggest(s,level),null);
 assert.throws(()=>E.play(s,0),/남은 돌/);
 s=E.play(E.play(s,null),null);assert.equal(s.phase,'scoring');assert.throws(()=>E.resume(s),/소진/);assert.equal(E.finish(s).phase,'finished');
});
function setup(black,white,size=5){const s=E.initialState(size);black.forEach(i=>s.board[i]=1);white.forEach(i=>s.board[i]=2);s.history=[E.key(s.board)];return s;}
test('Go: sizes, turn order and immutable placement',()=>{for(const n of [9,13,19])assert.equal(E.initialState(n).board.length,n*n);const s=E.initialState(),t=E.play(s,40);assert.equal(s.board[40],0);assert.equal(t.board[40],1);assert.equal(t.turn,2);assert.throws(()=>E.play(t,40));for(const i of [-1,81,1.5,'4',undefined])assert.throws(()=>E.play(s,i));});
test('Go: edge neighbors, groups and shared liberties',()=>{assert.deepEqual(E.neighbors(0,5),[5,1]);const s=setup([11,12],[]);assert.equal(E.group(s.board,11,5).stones.length,2);assert.equal(E.group(s.board,11,5).liberties.size,6);});
test('Go: capture entire group and multi-group capture',()=>{let s=setup([6,7,10,13,16],[11,12]);let t=E.play(s,17);assert.equal(t.captures[1],2);assert.equal(t.board[11],0);s=setup([1,3,5,9,11,13],[6,8]);t=E.play(s,7);assert.equal(t.captures[1],2);});
test('Go: suicide forbidden, capture before self-capture allowed',()=>{assert.throws(()=>E.play(setup([],[7,11,13,17]),12),/자충/);const t=E.play(setup([2,6,8],[7,11,13,17]),12);assert.equal(t.captures[1],1);assert.equal(t.board[12],1);});
test('Go: ko and longer repetition are rejected without mutating state',()=>{const s=setup([2,6,8],[7,11,13,17]);const t=E.play(s,12);assert.throws(()=>E.play(t,7),/반복/);const u=E.play(E.play(t,24),20);assert.doesNotThrow(()=>E.play(u,7));const ordinary=E.initialState();const future=E.play(ordinary,0);ordinary.history.push(E.key(future.board));assert.throws(()=>E.play(ordinary,0),/반복/);});
test('Go: two passes enter scoring; resume retains turn and history',()=>{const s=E.play(E.play(E.initialState(),null),null);assert.equal(s.phase,'scoring');assert.equal(s.turn,1);assert.throws(()=>E.play(s,0));const t=E.resume(s);assert.equal(t.phase,'play');assert.equal(t.passes,0);assert.deepEqual(t.history,s.history);assert.doesNotThrow(()=>E.play(t,0));});
test('Go: area scores living stones, not prisoners; neutral region and komi',()=>{let s=setup([0],[24]);s.captures=[0,100,0];let t=E.score(s);assert.equal(t.black,1);assert.equal(t.white,7.5);s=setup([1,5,7,11],[24]);t=E.score(s);assert.equal(t.territory[1],2);assert.equal(t.black,6);});
test('Go: dead groups toggle together and final score is immutable',()=>{let s=setup([0],[11,12]);s.phase='scoring';s=E.toggleDead(s,11);assert.equal(s.dead.length,2);assert.equal(E.toggleDead(s,12).dead.length,0);const f=E.finish(s);assert.equal(f.result.reason,'score');assert.equal(f.phase,'finished');assert.throws(()=>E.toggleDead(f,11));assert.throws(()=>E.resume(f));});
test('Go: save replays moves, scoring and resignation; corrupted data rejected',()=>{const data={version:1,size:9,moves:[{type:'play',index:40},{type:'play',index:null},{type:'play',index:null},{type:'dead',index:40},{type:'finish'}]};assert.equal(E.restore(data).result.winner,2);assert.throws(()=>E.restore({...data,moves:[{type:'play',index:999}]}));assert.throws(()=>E.restore({...data,version:9}));assert.equal(E.restore({...data,moves:[{type:'resign',color:1}]}).result.winner,2);});
test('Go: all 12 lessons are legal and teaching outcomes hold',()=>{assert.equal(L.length,12);L.forEach(l=>assert.doesNotThrow(()=>E.play(setup(l.black,l.white),l.answer)));for(const [i,captured] of [[2,1],[5,1],[6,2],[7,1]])assert.equal(E.play(setup(L[i].black,L[i].white),L[i].answer).captures[1],captured);const s=E.play(setup(L[10].black,[]),7);assert.deepEqual([...E.group(s.board,7,5).liberties].sort((a,b)=>a-b),[6,8,15,16,17,18,19]);});
test('Go: AI all levels returns legal moves and conserves stones in self-play',()=>{for(const level of [0,1,2,3]){let s=E.initialState(9);for(let turn=0;turn<130&&s.phase==='play';turn++){const prior=JSON.stringify(s),i=E.suggest(s,level,()=>.4);assert.equal(JSON.stringify(s),prior);s=E.play(s,i);const placed=s.ply;assert.ok(s.board.filter(Boolean).length+s.captures[1]+s.captures[2]<=placed);for(let p=0;p<s.board.length;p++)if(s.board[p])assert.ok(E.group(s.board,p,s.size).liberties.size>0);}}});
